name: Convert and Release

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install pandoc
      run: sudo apt-get install --yes pandoc texlive

    - name: Ensure build directory exists
      run: mkdir -vp ./build

    - name: Convert Markdown to PDF
      run: pandoc src/professional.md --standalone --output=build/professional.pdf

    - name: Convert Markdown to DOCX
      run: pandoc src/professional.md --standalone --output=build/professional.docx

    - name: Convert Markdown to RTF
      run: pandoc src/professional.md --standalone --output=build/professional.rtf

    - name: Convert Markdown to HTML
      run: pandoc src/professional.md --standalone --output=build/professional.html
    
    - name: Ensure complete Markdown
      run: pandoc src/professional.md --standalone --output=build/professional.md

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: converted-files
        path: |
          build/professional.pdf
          build/professional.docx
          build/professional.rtf
          build/professional.html
          build/professional.md

  release:
    needs: convert
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: converted-files
        path: ./artifacts

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/professional.pdf
        asset_name: professional.pdf
        asset_content_type: application/pdf

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/professional.docx
        asset_name: professional.docx
        asset_content_type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/professional.rtf
        asset_name: professional.rtf
        asset_content_type: application/rtf

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/professional.html
        asset_name: professional.html
        asset_content_type: text/html
